name: Build target image
on:
  workflow_call:
    inputs:
      registry:
        description: "Docker Registry"
        required: true
        type: string
        default: "ghcr.io"
      image:
        description: "Image"
        required: true
        type: string
      version:
        description: "Version"
        required: true
        type: string
      platform:
        description: "Platform"
        required: true
        type: string
      arch:
        description: "Architecture"
        required: true
        type: string
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ${{ (inputs.platform == 'linux' && (inputs.arch == 'arm64' || inputs.arch == 'arm')) && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set tags
        id: tags
        run: |
          echo "image=${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.arch }}" >> $GITHUB_OUTPUT
          echo "tag=${{ inputs.version }}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: etc/docker/Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
          provenance: false
          sbom: false
          build-args: |
            ARCH=${{ inputs.arch }}
            PLATFORM=${{ inputs.platform }}
            VERSION=${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
